### ISSUE TITLE
Cron workflows got disabled after 60 days of inactivity

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/bcd-utils#23]
The workflow that updates the API periodically [got auto disabled](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow):
![_1](https://github.com/mdn/bcd-utils/assets/87750369/f1637238-52f3-4758-990b-858faf10b696)

I believe due to this latest BCD data is not reflecting on the MDN site.

To keep these workflows running permanently, can we trigger these workflows from `mdn/content` repo (instead of cron here) as the content repo is always active?

**Comment by bsmth** [comment]
Wasn't there a discussion about moving these into BCD itself?

CCing @queengooborg

**Comment by queengooborg** [comment]
> Wasn't there a discussion about moving these into BCD itself?

No, this repository specifically contains helpers for Yari.  We have discussed adding an API to BCD, but this is not it.
